version: '3.9'

services:
  php:
    build:
      context: ./docker/php
    container_name: symfony-php
    volumes:
      - ./app:/var/www/html
    environment:
      - APP_ENV=dev
    depends_on:
      - db

  nginx:
    image: nginx:1.25
    container_name: symfony-nginx
    ports:
      - "8080:80"   # host:container
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    image: postgres:16
    container_name: symfony-postgres
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: symfony-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  mercure:
    image: dunglas/mercure
    container_name: symfony-mercure
    environment:
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: '!ChangeMeMercureJwtSecret!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeMeMercureJwtSecret!'
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins http://localhost:8080 http://localhost http://127.0.0.1:8080
    ports:
      - "8081:80"

volumes:
  pgdata:
