nelmio_api_doc:
    path: /api/docs
    methods: [GET]
    defaults:
        _controller: 'Nelmio\\ApiDocBundle\\Controller\\SwaggerUiController::indexAction'

nelmio_api_doc_json:
    path: /api/docs.json
    methods: [GET]
    defaults:
        _controller: 'Nelmio\\ApiDocBundle\\Controller\\SwaggerUiController::swaggerAction'
