nelmio_api_doc:
    documentation:
        openapi: 3.0.0
        info:
            title: 'Matching Service API'
            description: 'OpenAPI documentation for matching service endpoints.'
            version: '1.0.0'
    areas:
        default:
            path_patterns:
                - ^/api
